[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esups-supply-prepositioning"
version = "0.1.0"
# etc...

[project.optional-dependencies]
sphinx = ["jupyter-book[sphinx]>=1.0"]
